# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tinder}
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brandon Keepers"]
  s.date = %q{2010-10-09}
  s.description = %q{A Ruby API for interfacing with Campfire, the 37Signals chat application.}
  s.email = %q{brandon@opensoul.org}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = ["init.rb"] + Dir["lib/**/*.rb"]
  s.homepage = %q{http://github.com/collectiveidea/tinder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{tinder}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the Campfire API}
  s.test_files = Dir["spec/**/*.rb"]

  s.add_runtime_dependency(%q<activesupport>, [">= 0"])
  s.add_runtime_dependency(%q<httparty>, [">= 0"])
  s.add_runtime_dependency(%q<mime-types>, [">= 0"])
  s.add_runtime_dependency(%q<twitter-stream>, [">= 0"])
  s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
  s.add_development_dependency(%q<json>, [">= 0"])
  s.add_development_dependency(%q<rspec>, ["~> 1.3"])
  s.add_development_dependency(%q<fakeweb>, [">= 0"])
end

